import { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  // ── BOLSAS ──────────────────────────────────────────────────────────────
  {
    id: "demo-1",
    slug: "frasqueira-quadrada",
    name: "Frasqueira Quadrada",
    description: "Frasqueira personalizada com tema à escolha. Material resistente, acabamento perfeito.",
    category: "bolsas",
    price_cents: 1000,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    slug: "mochilinha-slim",
    name: "Mochilinha Slim",
    description: "Mochilinha infantil personalizada, leve e resistente. Tema à escolha.",
    category: "bolsas",
    price_cents: 1200,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    slug: "bolsa-bau-midi",
    name: "Bolsa Báu Midi",
    description: "Bolsa no formato báu, personalizada com tema à escolha.",
    category: "bolsas",
    price_cents: 1600,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-4",
    slug: "bolsa-bau-g",
    name: "Bolsa Báu G",
    description: "Versão grande da Bolsa Báu. Pedido mínimo de 10 unidades.",
    category: "bolsas",
    price_cents: 2000,
    compare_at_price_cents: null,
    min_order: 10,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-5",
    slug: "bolsa-trapezio-transparente",
    name: "Bolsa Trapézio com Transparente",
    description: "Bolsa no formato trapézio com visor transparente, personalizada.",
    category: "bolsas",
    price_cents: 1400,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1591561954555-607968c989ab?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-6",
    slug: "bolsinha-bolear",
    name: "Bolsinha Bolear",
    description: "Bolsinha redonda em formato de bola, personalizada com tema à escolha.",
    category: "bolsas",
    price_cents: 800,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-7",
    slug: "maletinha",
    name: "Maletinha",
    description: "Maletinha personalizada, ideal para lembrancinha de festa.",
    category: "bolsas",
    price_cents: 800,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4b4283?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-8",
    slug: "meia-lua-3d",
    name: "Meia Lua 3D",
    description: "Bolsa meia-lua 3D personalizada, tema à escolha.",
    category: "bolsas",
    price_cents: 1150,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1614179924047-e1ab49a0a0cf?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-9",
    slug: "bag-click",
    name: "Bag Click",
    description: "Bag com fechamento click, personalizada com seu tema.",
    category: "bolsas",
    price_cents: 1000,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-10",
    slug: "bolsa-dora-lateral",
    name: "Bolsa Dora Lateral",
    description: "Bolsa no formato Dora, personalizada. Tema à escolha.",
    category: "bolsas",
    price_cents: 1200,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-11",
    slug: "mochila-saco-personalizada",
    name: "Mochila Saco Personalizada",
    description: "Mochila saco 20x27cm, personalizada com tema à escolha.",
    category: "bolsas",
    price_cents: 600,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  // ── NECESSAIRES ─────────────────────────────────────────────────────────
  {
    id: "demo-12",
    slug: "necessaire-simples",
    name: "Necessaire Simples",
    description: "Personalizada frente e verso. Tema à escolha.",
    category: "necessaires",
    price_cents: 700,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1556742044-3c52d6e88c62?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-13",
    slug: "necessaire-box",
    name: "Necessaire Box Personalizada",
    description: "Tamanho 14x20cm, personalizada. Tema à escolha.",
    category: "necessaires",
    price_cents: 1000,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-14",
    slug: "estojo-personalizado",
    name: "Estojo Personalizado",
    description: "Personaliza da forma que desejar. Tema à escolha.",
    category: "necessaires",
    price_cents: 1500,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-15",
    slug: "estojo-super",
    name: "Estojo Super",
    description: "Pedido mínimo de 10 unidades. Personalizado com tema à escolha.",
    category: "necessaires",
    price_cents: 850,
    compare_at_price_cents: null,
    min_order: 10,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-16",
    slug: "quadrangular-17x17",
    name: "Quadrangular 17x17",
    description: "Necessaire quadrada 17x17cm, personalizada com tema à escolha.",
    category: "necessaires",
    price_cents: 1000,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-17",
    slug: "frasqueira-redonda",
    name: "Frasqueira Redonda",
    description: "Frasqueira no formato redondo, personalizada com tema à escolha.",
    category: "necessaires",
    price_cents: 1400,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-18",
    slug: "retangular-com-visor",
    name: "Retangular com Visor",
    description: "Pedido mínimo de 10 unidades. Necessaire retangular com visor transparente.",
    category: "necessaires",
    price_cents: 1200,
    compare_at_price_cents: null,
    min_order: 10,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-19",
    slug: "retangular-com-2-visor",
    name: "Retangular com 2 Visores",
    description: "Pedido mínimo de 10 unidades. Necessaire com 2 visores transparentes.",
    category: "necessaires",
    price_cents: 1400,
    compare_at_price_cents: null,
    min_order: 10,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-20",
    slug: "mini-ecobag-cristal",
    name: "Mini Ecobag Cristal",
    description: "Ecobag mini em material cristal, personalizada.",
    category: "necessaires",
    price_cents: 790,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-21",
    slug: "meia-bag-slim",
    name: "Meia Bag Slim",
    description: "Bag slim meia-lua, personalizada com tema à escolha.",
    category: "necessaires",
    price_cents: 750,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1614179924047-e1ab49a0a0cf?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  // ── COPOS ───────────────────────────────────────────────────────────────
  {
    id: "demo-22",
    slug: "copo-twister-com-canudo",
    name: "Copo Twister com Canudo",
    description: "Pedido mínimo de 10 unidades. Personalizado.",
    category: "copos",
    price_cents: 500,
    compare_at_price_cents: null,
    min_order: 10,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-23",
    slug: "caneca-personalizada",
    name: "Caneca Personalizada 325ml",
    description: "Caneca 325ml personalizada. Tema à escolha.",
    category: "copos",
    price_cents: 4000,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-24",
    slug: "caneca-acrilica-300ml",
    name: "Caneca Acrílica 300ml",
    description: "Personalização apenas na frente. Tema à escolha.",
    category: "copos",
    price_cents: 500,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-25",
    slug: "copo-long-drink",
    name: "Copo Long Drink",
    description: "Personalização apenas na frente. Tema à escolha.",
    category: "copos",
    price_cents: 450,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-26",
    slug: "copo-brasileirinho",
    name: "Copo Brasileirinho",
    description: "Pedido mínimo de 10 unidades. Personalizado.",
    category: "copos",
    price_cents: 400,
    compare_at_price_cents: null,
    min_order: 10,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-27",
    slug: "copo-descartavel-personalizado",
    name: "Copo Descartável Personalizado",
    description: "Pedido mínimo de 30 unidades. Personalizado.",
    category: "copos",
    price_cents: 200,
    compare_at_price_cents: null,
    min_order: 30,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  // ── LEMBRANCINHAS ───────────────────────────────────────────────────────
  {
    id: "demo-28",
    slug: "saquinho-de-doce-personalizado",
    name: "Saquinho de Doce Personalizado",
    description: "Tamanho 14x20cm. Personalizado com tema à escolha.",
    category: "lembrancinhas",
    price_cents: 350,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-29",
    slug: "kit-soneca",
    name: "Kit Soneca",
    description: "Kit soneca personalizado com tema à escolha.",
    category: "lembrancinhas",
    price_cents: 2000,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-30",
    slug: "porta-moedas-simples",
    name: "Porta Moedas Simples",
    description: "Pedido mínimo de 15 unidades. Personalizado.",
    category: "lembrancinhas",
    price_cents: 320,
    compare_at_price_cents: null,
    min_order: 15,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-31",
    slug: "porta-moedas-mini-box",
    name: "Porta Moedas Mini Box",
    description: "Pedido mínimo de 10 unidades. Personalizado.",
    category: "lembrancinhas",
    price_cents: 430,
    compare_at_price_cents: null,
    min_order: 10,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-32",
    slug: "cofrinho-personalizado",
    name: "Cofrinho Personalizado",
    description: "Arte no papel fotográfico. Tema à escolha.",
    category: "lembrancinhas",
    price_cents: 450,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-33",
    slug: "almofada-de-colorir",
    name: "Almofada de Colorir Personalizada",
    description: "Tamanho 15x25cm. Personalizada com tema à escolha.",
    category: "lembrancinhas",
    price_cents: 900,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-34",
    slug: "lousa-magica",
    name: "Lousa Mágica",
    description: "Acompanha canetinha. Personalizada com tema à escolha.",
    category: "lembrancinhas",
    price_cents: 700,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-35",
    slug: "kit-lapis-marca-pagina",
    name: "Kit Lápis + Marca Página Personalizado",
    description: "Combo lápis + marca página, personalizado.",
    category: "lembrancinhas",
    price_cents: 350,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  // ── CHAVEIROS ───────────────────────────────────────────────────────────
  {
    id: "demo-36",
    slug: "botton-32mm",
    name: "Botton 32mm",
    description: "Já vai embalado. Pode ser imã ou chaveiro personalizado.",
    category: "chaveiros",
    price_cents: 300,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-37",
    slug: "botton-44mm",
    name: "Botton 44mm",
    description: "Pode ser imã ou chaveiro personalizado.",
    category: "chaveiros",
    price_cents: 450,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-38",
    slug: "botton-58mm",
    name: "Botton 58mm",
    description: "Pode ser imã ou chaveiro personalizado.",
    category: "chaveiros",
    price_cents: 600,
    compare_at_price_cents: null,
    min_order: null,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-39",
    slug: "almochaveiro-personalizado",
    name: "Almochaveiro Personalizado",
    description: "Pedido mínimo de 20 unidades. Personalizado.",
    category: "chaveiros",
    price_cents: 200,
    compare_at_price_cents: null,
    min_order: 20,
    min_order_value_cents: null,
    stock: 99,
    images: ["https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80"],
    active: true,
    created_at: new Date().toISOString(),
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  bolsas: "Bolsas",
  necessaires: "Necessaires & Estojos",
  copos: "Copos Personalizados",
  lembrancinhas: "Lembrancinhas",
  chaveiros: "Chaveiros & Bottons",
  outros: "Outros",
};
